before_script:
  - "ruby --version"
  - "bundle exec rake test_app"
script: "bundle exec rake"
notifications:
  irc: "irc.freenode.org#spree"
branches:
  only:
    - master
    - namespace
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
